import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import run from "@/data/qiskitNotebookRun.json";

/**
 * Execution report for notebooks/QuantumSynapseFabric_Qiskit_Verified.ipynb.
 *
 * src/data/qiskitNotebookRun.json is generated by actually executing the notebook
 * with nbclient on the pinned Qiskit stack. Nothing on this page is illustrative:
 * every status and output line comes from that run.
 */

type CellRun = {
  index: number;
  title: string;
  status: string;
  output: string;
  error: string | null;
};

const cells = run.cells as CellRun[];
const failing = cells.filter((c) => c.status !== "passed");

export default function QiskitVerification() {
  return (
    <main className="container mx-auto max-w-4xl px-4 py-10 space-y-6">
      <header className="space-y-2">
        <h1 className="text-3xl font-bold">Qiskit Notebook Verification</h1>
        <p className="text-muted-foreground">
          Cell-by-cell execution report for <code>notebooks/{run.notebook}</code>, run with
          nbclient on {run.runtime}.
        </p>
        <div className="flex flex-wrap items-center gap-2">
          <Badge>{cells.length - failing.length} passed</Badge>
          <Badge variant={failing.length ? "destructive" : "secondary"}>
            {failing.length} failing
          </Badge>
          <span className="text-xs text-muted-foreground">
            last run {new Date(run.ran_at).toUTCString()}
          </span>
        </div>
      </header>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Failing cells</CardTitle>
          <CardDescription>
            Cells that raised an exception during the run above.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {failing.length === 0 ? (
            <p className="text-sm text-muted-foreground">
              None — every code cell ran to completion and its own assertions passed.
            </p>
          ) : (
            <ul className="space-y-2 text-sm">
              {failing.map((c) => (
                <li key={c.index} className="rounded-md border p-3">
                  <p className="font-medium">Cell {c.index} — {c.title}</p>
                  <p className="text-destructive text-xs mt-1">{c.error}</p>
                </li>
              ))}
            </ul>
          )}
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="text-base">Required libraries</CardTitle>
          <CardDescription>
            Colab preinstalls none of the Qiskit packages, so the first cell installs them.
          </CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="flex flex-wrap gap-2">
            {run.libraries.map((lib) => (
              <Badge key={lib} variant="outline">
                <code>{lib}</code>
              </Badge>
            ))}
          </div>
          <pre className="overflow-x-auto rounded-md bg-muted p-3 text-xs">
{`!pip install -q qiskit==2.5.2 qiskit-aer==0.17.2`}
          </pre>
          <p className="text-sm text-muted-foreground">
            No GPU, API key or network access beyond the install is needed. nbformat, nbclient
            and ipykernel are only required to run the notebook headlessly, as done here.
          </p>
        </CardContent>
      </Card>

      <Alert>
        <AlertTitle>What this does and does not show</AlertTitle>
        <AlertDescription>
          QRNG and GHZ are genuine Qiskit circuit simulation on a classical simulator — not
          hardware entropy and not a claim of quantum advantage. BB84 correctly simulates the
          protocol's math, including why measurement disturbance raises QBER, but provides no
          real security without a physical quantum channel. Sampled quantities such as the
          eavesdropper QBER vary between runs.
        </AlertDescription>
      </Alert>

      <div className="space-y-4">
        {cells.map((c) => (
          <Card key={c.index}>
            <CardHeader>
              <div className="flex items-center justify-between gap-3">
                <CardTitle className="text-base">
                  Cell {c.index} — <code className="text-sm">{c.title}</code>
                </CardTitle>
                <Badge variant={c.status === "passed" ? "default" : "destructive"}>
                  {c.status.toUpperCase()}
                </Badge>
              </div>
            </CardHeader>
            <CardContent>
              <pre className="overflow-x-auto rounded-md bg-muted p-3 text-xs whitespace-pre-wrap">
{c.output || "(no output)"}
              </pre>
            </CardContent>
          </Card>
        ))}
      </div>
    </main>
  );
}
