// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/echo.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var echo_default = defineTool({
  name: "echo",
  title: "Echo",
  description: "Echo the input text back to the caller. Useful for verifying the MCP connection is working.",
  inputSchema: {
    text: z.string().min(1).describe("Text to echo back.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: ({ text }) => ({
    content: [{ type: "text", text }]
  })
});

// src/lib/mcp/tools/app-info.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var app_info_default = defineTool2({
  name: "get_app_info",
  title: "Get app info",
  description: "Return a short description of this app (Quantum Coin) and a list of its main routes so an assistant can direct users to the right page.",
  inputSchema: {},
  annotations: {
    readOnlyHint: true,
    idempotentHint: true,
    openWorldHint: false
  },
  handler: () => {
    const info = {
      name: "Quantum Coin",
      description: "A blockchain + quantum-simulation web app with quantum circuit visualizer, mining dashboard, DAO governance, crypto market data, and a realtime demo.",
      routes: [
        { path: "/", purpose: "Home / marketing landing page" },
        { path: "/quantum-lab", purpose: "Quantum sequence, BB84 QKD demo, Grover/Shor solver panels" },
        { path: "/realtime-demo", purpose: "Supabase Realtime + IBM Quantum QASM runner demo" },
        { path: "/quantum-computing", purpose: "Quantum computing overview" },
        { path: "/crypto-market", purpose: "Live crypto market data" },
        { path: "/dao", purpose: "DAO governance" },
        { path: "/wallet", purpose: "User wallet integrations (MetaMask, Phantom, Pera)" },
        { path: "/profile", purpose: "Signed-in user profile" }
      ]
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/crypto-price.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var crypto_price_default = defineTool3({
  name: "get_crypto_price",
  title: "Get crypto price",
  description: "Fetch the current USD price and 24h change for a cryptocurrency by CoinGecko id (e.g. 'bitcoin', 'ethereum', 'solana').",
  inputSchema: {
    coinId: z2.string().trim().min(1).describe("CoinGecko coin id, e.g. 'bitcoin' or 'ethereum'.")
  },
  annotations: {
    readOnlyHint: true,
    idempotentHint: false,
    openWorldHint: true
  },
  handler: async ({ coinId }) => {
    const url = `https://api.coingecko.com/api/v3/simple/price?ids=${encodeURIComponent(
      coinId
    )}&vs_currencies=usd&include_24hr_change=true`;
    const res = await fetch(url, { headers: { accept: "application/json" } });
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `CoinGecko error: ${res.status} ${res.statusText}` }],
        isError: true
      };
    }
    const data = await res.json();
    const entry = data[coinId];
    if (!entry) {
      return {
        content: [{ type: "text", text: `No price data for '${coinId}'.` }],
        isError: true
      };
    }
    const payload = {
      coinId,
      usd: entry.usd,
      change24hPct: entry.usd_24h_change
    };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "quantum-coin-mcp",
  title: "Quantum Coin MCP",
  version: "0.1.0",
  instructions: "Tools for the Quantum Coin app. Use `echo` to verify connectivity, `get_app_info` to learn what routes and features the app exposes, and `get_crypto_price` to fetch live USD prices for a given CoinGecko coin id.",
  tools: [echo_default, app_info_default, crypto_price_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
